ROOTDIR = ..

include $(ROOTDIR)/config/define.mk

PRGSRC += 	\
			utopfs.cpp \
			$(NULL)

PRGEXE = 	utopfs


SCRIPTS =	\
			$(NULL)

CFG =		\
			$(NULL)

include $(ROOTDIR)/config/depend.mk

# External Package Dependencies
include $(ROOTDIR)/config/extdep/fuse.mk
