ROOTDIR = ..

include $(ROOTDIR)/config/define.mk

SUBDIRS =	\
			BDBBlockStore \
			DefaultLogger \
			FSBlockStore \
			S3BlockStore \
			UTFileSystem \
			$(NULL)

include $(ROOTDIR)/config/depend.mk

# Local Variables:
# mode: Makefile
# tab-width: 4
# End:
