#!/bin/env python

import os
import sys
import time

import utp
import utp.BlockStore
import utp.FileSystem

try:
    bstype = sys.argv[1]
    path = sys.argv[2]
    size = int(sys.argv[3])
    fstype = sys.argv[4]
    fsid = sys.argv[5]
    passphrase = sys.argv[6]
    uname = sys.argv[7]
    gname = sys.argv[8]

    bs = utp.BlockStore.create(bstype, "tmp", size, (path,))
    utp.FileSystem.mkfs(fstype, bs, fsid, passphrase, uname, gname, ())

except utp.Error, ex:
    print ex[0]['what']

except:
    print "Unexpected error:", sys.exc_info()[0]
    raise

