#!/bin/env python

import os
import sys
import time

import utp
import utp.BlockStore

bucket = sys.argv[1]
print "removing bucket %s" % bucket

key_id = os.environ['S3_ACCESS_KEY_ID']
secret = os.environ['S3_SECRET_ACCESS_KEY']

try:
    bsargs = ("--s3-access-key-id=%s" % key_id,
              "--s3-secret-access-key=%s" % secret,
              "--bucket=%s" % bucket)

    try:
        utp.BlockStore.destroy("S3BS", bsargs)

    except utp.NotFoundError, ex:
        # It's ok if it doesn't exist ...
        pass

except utp.Error, ex:
    print ex[0]['what']

except:
    print "Unexpected error:", sys.exc_info()[0]
    raise
