#!/bin/env python

import sys

import utp
import utp.BlockStore
import utp.FileSystem

try:
    # Get the FileSystem singleton.
    fs = utp.FileSystem.instance()

    # Make a new filesystem.
    fs.fs_mkfs("myfs");

    # Stat something.
    print fs.fs_getattr("/.utopfs");
    
except utp.Error, ex:
    print ex[0]['what']

except:
    print "Unexpected error:", sys.exc_info()[0]
    raise
