#!/bin/env python

import sys

import utp
import utp.BlockStore
import utp.FileSystem

import time

import CONFIG
from lenhack import *

try:
    bspath = "test.bs"
    CONFIG.remove_bs(bspath)
    bs = utp.BlockStore.create(CONFIG.BSTYPE,
                               CONFIG.BSSIZE,
                               CONFIG.BSARGS(bspath))

    # Insert a single SHN.
    node = utp.SignedHeadNode(("fsid", "rootref", 0, time.time() * 1e6, 0, 0))
    bs.bs_head_insert(node)

    bs.bs_close()

except utp.Error, ex:
    print ex[0]['what']

except:
    print "Unexpected error:", sys.exc_info()[0]
    raise
