#!/bin/env python

import sys

import utp
import utp.BlockStore
import utp.FileSystem

try:
    # Find the BlockStore singleton.
    bs = utp.BlockStore.instance()

    # Create the BlockStore at a path.
    bs.bs_create("myfsbs")

    # Open the FileSystem.
    fs = utp.FileSystem.instance()
    
    # Close the BlockStore.
    bs.bs_close()

except utp.Error, ex:
    print ex[0]['what']

except Exception, ex:
    print ex
