#!/bin/env python

import sys

import utp
import utp.BlockStore
import utp.FileSystem

import time

import CONFIG
from lenhack import *

try:
    bspath = "test.bs"
    bs = utp.BlockStore.open(CONFIG.BSTYPE,
                             "rootbs",
                             CONFIG.BSARGS(bspath))

    node0 = utp.SignedHeadEdge(("fsid", 0, 0, 0, 0, 0))
    shns = bs.bs_head_furthest(node0)
    
    print shns

    bs.bs_close()

except utp.Error, ex:
    print ex[0]['what']

except:
    print "Unexpected error:", sys.exc_info()[0]
    raise
