#!/bin/env python

import sys

import utp
import utp.BlockStore

try:
    # Find the BlockStore singleton.
    bs = utp.BlockStore.instance()

    # Create the BlockStore at a path.
    bs.bs_create("myfsbs")

    # Put a block of data.
    bs.bs_put_block(buffer("thekey"), buffer("thevalue"))

    # Get a block of data.
    b = bs.bs_get_block(buffer("thekey"))
    print b
    
    bs.bs_del_block(buffer("thekey"))

    # Put a second block of data.
    bs.bs_put_block(buffer("thekey2"), buffer("thevalue2"))
    
    # Get the block of data.
    b = bs.bs_get_block(buffer("thekey2"))
    print b

    # Put a bad block of data.
    bs.bs_put_block(buffer("thekey2"), buffer("thevalue2"))


    # try geting a block of data that doesn't exist
    #b = bs.bs_get_block(buffer("thekey3"))
    #print b

    
    # Close the BlockStore.
    bs.bs_close()

except utp.Error, ex:
    print ex[0]['what']

except Exception, ex:
    print ex
