#!/bin/env python

import os
import sys
import shutil

import utp
import utp.BlockStore
import utp.FileSystem
import utp.PyDirEntryFunc

class DirEntryPrinter(utp.PyDirEntryFunc.PyDirEntryFunc):
    def __init__(self):
        utp.PyDirEntryFunc.PyDirEntryFunc.__init__(self)

    def def_entry(self, name, statbuf, offset):
        print "def_entry", name, statbuf, offset

try:
    # Use the blockstore from the prior test
    bspath = "test2.bs"

    # Get the FileSystem singleton.
    fs = utp.FileSystem.instance()

    # Mount the existing filesystem.
    fs.fs_mount(bspath, "");

    # Stat something.
    print fs.fs_getattr("/.utopfs");

    # See if readdir works
    decb = DirEntryPrinter()
    fs.fs_readdir("/.utopfs", 0, decb)

    # Open a file
    fs.fs_open("/foo", os.O_RDONLY)

    # Stat the file
    print fs.fs_getattr("/foo")

    # Don't Clean up.
    # shutil.rmtree(bspath, True)  

except utp.Error, ex:
    print ex[0]['what']

except:
    print "Unexpected error:", sys.exc_info()[0]
    raise
