ROOTDIR = ..

include $(ROOTDIR)/config/define.mk

SUBDIRS =	\
			src \
			tests \
			pymod \
			$(NULL)

include $(ROOTDIR)/config/depend.mk

# Local Variables:
# mode: Makefile
# tab-width: 4
# End:
