ROOTDIR = ..

include $(ROOTDIR)/config/define.mk

PRGSRC += 	\
			utp.cpp \
			$(NULL)

PRGEXE = 	utp


SCRIPTS =	\
			runutp \
			$(NULL)

CFG =		\
			$(NULL)

include $(ROOTDIR)/config/depend.mk

# Dependencies

# External Package Dependencies
include $(ROOTDIR)/config/extdep/ACE.mk

# Module Dependencies
